export const BRIEFING_BEGIN_MARKER = "<!-- BEGIN RECLAW MEMORY SNAPSHOT -->";
export const BRIEFING_END_MARKER = "<!-- END RECLAW MEMORY SNAPSHOT -->";

export const LAST_SESSION_SUMMARY_BEGIN_MARKER = "<!-- BEGIN RECLAW SESSION SUMMARY -->";
export const LAST_SESSION_SUMMARY_END_MARKER = "<!-- END RECLAW SESSION SUMMARY -->";

export const AGENTS_MEMORY_GUIDANCE_BEGIN_MARKER = "<!-- BEGIN RECLAW MEMORY GUIDANCE -->";
export const AGENTS_MEMORY_GUIDANCE_END_MARKER = "<!-- END RECLAW MEMORY GUIDANCE -->";

export const MEMORY_NOTICE_BEGIN_MARKER = "<!-- BEGIN RECLAW MEMORY NOTICE -->";
export const MEMORY_NOTICE_END_MARKER = "<!-- END RECLAW MEMORY NOTICE -->";
