export const BRIEFING_BEGIN_MARKER = "<!-- BEGIN GENERATED BRIEFING -->";
export const BRIEFING_END_MARKER = "<!-- END GENERATED BRIEFING -->";

export const LAST_HANDOFF_BEGIN_MARKER = "<!-- BEGIN LAST HANDOFF -->";
export const LAST_HANDOFF_END_MARKER = "<!-- END LAST HANDOFF -->";

export const AGENTS_MEMORY_GUIDANCE_BEGIN_MARKER = "<!-- BEGIN ZETTELCLAW MEMORY GUIDANCE -->";
export const AGENTS_MEMORY_GUIDANCE_END_MARKER = "<!-- END ZETTELCLAW MEMORY GUIDANCE -->";

export const MEMORY_NOTICE_BEGIN_MARKER = "<!-- BEGIN ZETTELCLAW MEMORY NOTICE -->";
export const MEMORY_NOTICE_END_MARKER = "<!-- END ZETTELCLAW MEMORY NOTICE -->";
